addSbtPlugin("com.dwijnand"            % "sbt-dynver"          % "4.1.1")
addSbtPlugin("com.eed3si9n"            % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc"       % "2.0.0")
addSbtPlugin("com.typesafe.sbt"        % "sbt-native-packager" % "1.8.1")
addSbtPlugin("de.heikoseeberger"       % "sbt-header"          % "5.6.0")
addSbtPlugin("org.scalameta"           % "sbt-scalafmt"        % "2.4.2")
