[package]
edition = "2018"
name = "echo-client"
version = "0.1.0"

[dependencies]
prost = "0.8" # required in that particular version by tonic 0.5
structopt = "0.3"
tokio = {version = "1.0", features = ["macros", "rt-multi-thread"]}
tonic = "0.5"

[build-dependencies]
tonic-build = "0.5"
